import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} overflow-x-hidden>
        <main className="flex min-h-screen flex-col items-center justify-between pt-20 bg-white dark:bg-gray-950 text-black dark:text-white">
          <div className="z-10 w-full font-mono lg:flex lg:flex-col font-bold max-w-full">
            <Menu />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
